/* empty css                      */import{i,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&e(c)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const g="YOUR_ACTUAL_PIXABAY_API_KEY",y="https://pixabay.com/api/";function u(t,o=1){if(!t)return console.error("Search query is empty"),Promise.reject(new Error("Search query is empty"));const n=`${y}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=12`;return fetch(n).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>(e.hits.length===0&&console.warn("No images found for the query"),console.log("Fetched data:",e),e)).catch(e=>{throw console.error("Error fetching images:",e),e})}function m(t){const o=document.querySelector(".gallery"),n=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery__item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery__image" />
          <div class="image-info">
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
          </div>
        </a>`).join("");o.innerHTML=n}function L(){document.querySelector(".gallery").innerHTML=""}function d(){document.querySelector(".loader").classList.add("visible")}function f(){document.querySelector(".loader").classList.remove("visible")}const w=document.querySelector("#search-form"),q=document.querySelector("#load-more");let l="",a=1,h;w.addEventListener("submit",t=>{if(t.preventDefault(),l=t.target.elements.query.value.trim(),!l){i.error({title:"Error",message:"Please enter a search term."});return}L(),a=1,d(),u(l,a).then(o=>{o.hits.length===0?i.info({title:"No Results",message:"No images found. Please try a different search term."}):(m(o.hits),h=new p(".gallery a"))}).catch(o=>{i.error({title:"Error",message:"Failed to load images."})}).finally(()=>{f()})});q.addEventListener("click",()=>{a+=1,d(),u(l,a).then(t=>{m(t.hits),h.refresh()}).catch(t=>{i.error({title:"Error",message:"Failed to load more images."})}).finally(()=>{f()})});
//# sourceMappingURL=index.js.map
