/* empty css                      */import{i,S as h}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const p="46848734-31deafc513cc7a3bd94f1beea",g="https://pixabay.com/api/";function c(t){if(!t)return console.error("Search query is empty"),Promise.reject(new Error("Search query is empty"));const o=`${g}?key=${p}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=50`;return fetch(o).then(r=>{if(!r.ok)throw new Error("Network response was not ok");return r.json()}).then(r=>(r.hits.length===0&&console.warn("No images found for the query"),console.log("Fetched data:",r),r)).catch(r=>{throw console.error("Error fetching images:",r),r})}function u(t){const o=document.querySelector(".gallery"),r=t.map(n=>`
        <a href="${n.largeImageURL}" class="gallery__item">
          <img src="${n.webformatURL}" alt="${n.tags}" class="gallery__image" />
          <div class="image-info">
            <p>Likes: ${n.likes}</p>
            <p>Views: ${n.views}</p>
            <p>Comments: ${n.comments}</p>
            <p>Downloads: ${n.downloads}</p>
          </div>
        </a>`).join("");o.innerHTML=r}function y(){document.querySelector(".gallery").innerHTML=""}function f(){document.querySelector(".loader").classList.add("visible")}function d(){document.querySelector(".loader").classList.remove("visible")}const L=document.querySelector("#search-form");let a="",m;L.addEventListener("submit",t=>{if(t.preventDefault(),a=t.target.elements.query.value.trim(),!a){i.error({title:"Error",message:"Please enter a search term."});return}y(),f(),c(a,page).then(o=>{o.hits.length===0?i.info({title:"No Results",message:"No images found. Please try a different search term."}):(u(o.hits),m=new h(".gallery a"))}).catch(o=>{i.error({title:"Error",message:"Failed to load images."})}).finally(()=>{d()})});loadMoreButton.addEventListener("click",()=>{page+=1,f(),c(a,page).then(t=>{u(t.hits),m.refresh()}).catch(t=>{i.error({title:"Error",message:"Failed to load more images."})}).finally(()=>{d()})});
//# sourceMappingURL=index.js.map
