/* empty css                      */import{i,S as h}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&e(l)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const p="46848734-31deafc513cc7a3bd94f1beea",g="https://pixabay.com/api/";function c(t,o=1){if(!t)return console.error("Search query is empty"),Promise.reject(new Error("Search query is empty"));const n=`${g}?key=${p}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=50`;return fetch(n).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>(e.hits.length===0&&console.warn("No images found for the query"),console.log("Fetched data:",e),e)).catch(e=>{throw console.error("Error fetching images:",e),e})}function u(t){const o=document.querySelector(".gallery"),n=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery__item">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery__image" />
          <div class="image-info">
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
          </div>
        </a>`).join("");o.innerHTML=n}function y(){document.querySelector(".gallery").innerHTML=""}function f(){document.querySelector(".loader").classList.add("visible")}function d(){document.querySelector(".loader").classList.remove("visible")}const L=document.querySelector("#search-form");let a="",m;L.addEventListener("submit",t=>{if(t.preventDefault(),a=t.target.elements.query.value.trim(),!a){i.error({title:"Error",message:"Please enter a search term."});return}y(),f(),c(a,page).then(o=>{o.hits.length===0?i.info({title:"No Results",message:"No images found. Please try a different search term."}):(u(o.hits),m=new h(".gallery a"))}).catch(o=>{i.error({title:"Error",message:"Failed to load images."})}).finally(()=>{d()})});loadMoreButton.addEventListener("click",()=>{page+=1,f(),c(a,page).then(t=>{u(t.hits),m.refresh()}).catch(t=>{i.error({title:"Error",message:"Failed to load more images."})}).finally(()=>{d()})});
//# sourceMappingURL=index.js.map
